COMPILE_DEPS = [
    '//pipelines/simplebng:onos-pipelines-simplebng',
    '//protocols/p4runtime/model:onos-protocols-p4runtime-model',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
]

BUNDLES = [
    '//apps/dhcp/api:onos-apps-dhcp-api',
    '//apps/dhcp/app:onos-apps-dhcp-app',
]

onos_app (
  title = 'DHCP Server',
  category = 'Utility',
  url = 'http://onosproject.org',
  included_bundles = BUNDLES,
)
